### ISSUE TITLE
공통로직 및 개발환경 세팅

### ISSUE THREAD

**Issue by minje0204** [dnd-side-project/dnd-11th-9-backend#1]
## 🔥Description

- 기본 패키지 구조 생성
- base entity
- base response dto
- yaml 파일 생성
- DB 도커라이징
- ErrorCode / Global Exception 처리

## ✅ Todo

- [x] 기본 패키지 구조 생성
- [x] base entity
- [ ] base response dto
- [x] yaml 파일 생성
- [x] DB 도커라이징
- [x] ErrorCode / Global Exception 처리

**Comment by minje0204** [comment]
**남은 task**는 잠시 pending 해두었습니다
- DB 도커라이징
> 우선은 local dev를 사용하면서 DB 테이블이 수정됨에 따라 저희가 어떻게 작업하게 되는지 지켜보고 도커라이징하려고 아직 하지 않았습니다. 지금 생각나는 방법은, 빈 Mysql 인스턴스만 띄우고 ddl-auto: update 옵션을 통해서 ddl을 실행시키는건데, 좀 더 지켜볼게요!

- base response dto  
> 기존에 제가 생각했던 BaseResponseDto 클래스에서 code와 message 필드는 http 통신이 실패했을때 유의미한 필드가 되어서, 통신에 실패했을때 응답값으로 보내줄 dto(ErrorResponseDto)를 따로 만들면 BaseResponseDto없이 API별 요구사항을 만족하는 dto를 그대로 보내줘도 되지 않나 생각했어요


```Java
@Getter
@Schema
public class BaseResponseDto<T> {
    @Schema(description = "응답코드", example = "10001(게시글 중복 좋아요인 경우) / 10000(좋아요 요청을 한 게시글ID가 존재하지 않는 경우)")
    private int code;
    @Schema(description = "요청에 대한 응답 데이터", example = "에러가 발생한 경우 Empty String")
    private T data;
    @Schema(description = "에러에 대한 상세 메시지", example = "에러가 발생하지 않은 경우 Empty String")
    private String message;
    @Schema(description = "페이지네이션 관련 정보", example = "")
    @JsonInclude(Include.NON_NULL)
    private PageInfoResponseDto pageInfo;

    public BaseResponseDto(int code, T data, String message) {
        this.code = code;
        this.data = data;
        this.message = message;
        this.pageInfo = null;
    }

    public BaseResponseDto(int code, T data, String message, PageInfoResponseDto pageInfo) {
        this.code = code;
        this.data = data;
        this.message = message;
        this.pageInfo = pageInfo;
    }
}
```

**Comment by minje0204** [comment]
- DB 도커라이징 완료
